e-arbiter:
  swagger:
    contact-name: cyganki
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api
  clientUrl: ${E_ARB_HOST}:${E_ARB_CLIENT_PORT}
  proxyUrl: ${E_ARB_HOST}:${E_ARB_API_PORT}
  monitoringUrl: ${E_ARB_HOST}:${E_ARB_HYS_PORT}

logging:
  file: ${E_ARB_SUB_LOG_PATH}
  level:
    pl:
      cyganki: DEBUG