# Global file available for all modules
e-arbiter:
  name: e-Arbiter
  swagger.enabled: false
  clientUrl: ${E_ARB_HOST}:${E_ARB_CLIENT_PORT}
  proxyUrl: ${E_ARB_HOST}:${E_ARB_API_PORT}

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: INFO
    pl:
      cyganki: INFO
