e-arbiter:
  swagger:
    contact-name: cyganki
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api

logging:
    file: ${E_ARB_DEV_LOG_PATH}
    level:
      pl:
        cyganki: DEBUG