e-arbiter:
  service-name: Authentication Module

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: ${E_ARB_AUTH_PORT}

security:
  oauth2:
    client:
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope: user
    resource:
      userInfoUri: https://api.github.com/user