e-arbiter:
  swagger:
    enabled: true
    title: e-Arbiter - Authentication Module
    description: API for Authentication Module

spring:
  profiles: dev

server:
  port: ${E_ARB_DEV_AUTH_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      clientId: ${E_ARB_DEV_GH_CLIENT_ID}
      clientSecret: ${E_ARB_DEV_GH_CLIENT_SECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope: repo, user
    resource:
      userInfoUri: https://api.github.com/user
