e-arbiter:
  swagger:
    enabled: true
    title: e-Arbiter - Executor Module
    description: API for Executor Module

spring:
  profiles: dev

server:
  port: ${E_ARB_DEV_EXEC_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

docker:
  uri: unix:///var/run/docker.sock
  img: maciejmarczak/compilebox:latest
  cmd: python, run.py
  binding: ${E_ARB_DEV_EXEC_BINDING}:/solution
