spring:
  profiles: dev

server:
  port: ${E_ARB_HYS_PORT}
management:
  port: ${E_ARB_HYS_MAN_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  file: ${E_ARB_SUB_LOG_PATH}/e-arbiter-tournament-results.log