e-arbiter:
  swagger:
    title: e-Arbiter - Solution Repository Module
    description: API for Solution Repository Module

spring:
  profiles: dev

server:
  port: ${E_ARB_DEV_SOLR_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
