e-arbiter:
  swagger:
    enabled: true
    title: e-Arbiter - Tournament Module
    description: API for Tournament Module

spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  file: ${E_ARB_SUB_LOG_PATH}/e-arbiter-tournament.log