e-arbiter:
  service-name: Tournament Module
  salt: ${E_ARB_TOUR_MONGO_SALT}

server:
  port: ${E_ARB_TOUR_PORT}

spring:
  data:
    mongodb:
      host: ${E_ARB_TOUR_MONGO_HOST}
      port: ${E_ARB_TOUR_MONGO_PORT}
      database: e-arbiter
      username: ${E_ARB_TOUR_MONGO_USERNAME}
      password: ${E_ARB_TOUR_MONGO_PASSWORD}
  mail:
    host: ${E_ARB_TOUR_MAIL_HOST}
    port: ${E_ARB_TOUR_MAIL_PORT}
    username: ${E_ARB_TOUR_MAIL_USERNAME}
    password: ${E_ARB_TOUR_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}
          timeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}
          writetimeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}

logging:
  file: ${E_ARB_SUB_LOG_PATH}/e-arbiter-tournament.log