e-arbiter:
  swagger:
    enabled: true
    title: e-Arbiter - Tournament Results Module
    description: API for Tournament Results Module

spring:
  profiles: dev

  datasource:
    name: e-arbiter
    platform: h2
    url: jdbc:h2:mem:e-arbiter;DATABASE_TO_UPPER=true;IGNORECASE=true;

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true

  h2:
    console:
      enabled: true
      path: /db-console

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-test.xml

server:
  port: ${E_ARB_DEV_TRES_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
