e-arbiter:
  service-name: Tournament Module
  salt: ${E_ARB_DEV_TOUR_MONGO_SALT}

spring:
    mail:
      host: ${E_ARB_TOUR_MAIL_HOST}
      port: ${E_ARB_TOUR_MAIL_PORT}
      username: ${E_ARB_TOUR_MAIL_USERNAME}
      password: ${E_ARB_TOUR_MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true
            connectiontimeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}
            timeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}
            writetimeout: ${E_ARB_TOUR_MAIL_TIMEOUTS}

server:
  port: ${E_ARB_TOUR_PORT}