e-arbiter:
  swagger:
    enabled: true
    title: e-Arbiter - Tournament Module
    description: API for Tournament Module

spring:
  profiles: dev
  data:
    mongodb:
      host: ${E_ARB_DEV_TOUR_MONGO_HOST}
      port: ${E_ARB_DEV_TOUR_MONGO_PORT}
      database: e-arbiter

server:
  port: ${E_ARB_DEV_TOUR_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
