e-arbiter:
  service-name: Tournament Results Module

server:
  port: ${E_ARB_TRES_PORT}

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

logging:
  file: ${E_ARB_SUB_LOG_PATH}/e-arbiter-tournament-results.log